/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import NavbarMowo from 'components/NavbarMowo/NavbarMowo';
import MowoLandingPage from 'components/MowoLandingPage/MowoLandingPage';
import Footer from 'components/Footer/Footer';
import useMainPage from 'components/MainPage/useMainPage';

const Property1Desktop = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `20px 19px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
  height: 'auto',
});

const NavbarMowo1 = styled(NavbarMowo)(({ theme }) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

const MowoLandingPage1 = styled(MowoLandingPage)(({ theme }) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

const Footer1 = styled(Footer, {
  shouldForwardProp: (prop) => !['data'].includes(prop.toString()),
})(({ theme, data }) => ({
  alignSelf: `stretch`,
  height:
    data.currentVariant === 'Property1Mobile'
      ? `739px`
      : data.currentVariant === 'Property1Tablet'
      ? 'unset'
      : `391px`,
  margin: `0px`,
}));

function MainPage(props) {
  const { data } = useMainPage();

  return (
    <Property1Desktop className={props.className}>
      <NavbarMowo1 />
      <MowoLandingPage1 />
      <Footer1 data={data} />
    </Property1Desktop>
  );
}

export default MainPage;
