/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Link as MUILink } from '@mui/material';
import { styled } from '@mui/material/styles';
import ProductDropdownPopper from 'components/ProductDropdownPopper/ProductDropdownPopper';
import useNavbarMowo from 'components/NavbarMowo/useNavbarMowo';

const ScreenDesktop = styled('div', {
  shouldForwardProp: (prop) => !['data'].includes(prop.toString()),
})(({ data }) => ({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: data.currentVariant === 'screenmobile' ? `flex-start` : `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: 'auto',
}));

const Nav = styled('div', {
  shouldForwardProp: (prop) => !['data'].includes(prop.toString()),
})(({ data }) => ({
  backgroundColor: `rgba(23, 23, 23, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding:
    data.currentVariant === 'screentablet'
      ? `17px 40px`
      : data.currentVariant === 'screenmobile'
      ? `17px 20px`
      : `17px 180px 17px 20px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `72px`,
  margin: `0px`,
}));

const LeftSide = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const LogoWhiteNormal1 = styled('img')({
  height: `73px`,
  width: `236px`,
  objectFit: `cover`,
  margin: `0px`,
});

const Links = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 117px`,
});

const Product = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px 0px 0px 30px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const ProductDropdownPoppe = styled(ProductDropdownPopper)(({ theme }) => ({
  width: `100px`,
  height: `100px`,
  margin: `0px 0px 0px 8px`,
}));

const Product1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI Historic`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `0.5px`,
  textDecoration: `none`,
  lineHeight: `23px`,
  textTransform: `none`,
  margin: `0px`,
});

const Triangle = styled('img')({
  height: `8px`,
  width: `12px`,
  margin: `0px 0px 0px 8px`,
});

const Pricing = styled(MUILink)({
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI Historic`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `0.5px`,
  lineHeight: `23px`,
  textTransform: `none`,
  margin: `0px 0px 0px 39px`,
});

const RightSide = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-end`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const LogIn = styled(MUILink)({
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI Historic`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `0.5px`,
  lineHeight: `23px`,
  textTransform: `none`,
  margin: `0px`,
});

const SignUp = styled(MUILink)({
  color: `rgba(254, 136, 136, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI Historic`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `0.5px`,
  lineHeight: `23px`,
  textTransform: `none`,
  margin: `0px 0px 0px 33px`,
});

const XBurger = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 33px`,
});

const Hamburger = styled('img')({
  height: `31px`,
  width: `39px`,
  margin: `0px`,
});

const X = styled('img')({
  height: `31.17px`,
  width: `31.11px`,
  margin: `0px`,
});

const LeftSide1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const QuestLogoHeader = styled('img')({
  height: `37px`,
  width: `128px`,
  margin: `0px`,
});

const Links1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 40px`,
});

const Product2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px 0px 0px 30px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const ProductDropdownPoppe1 = styled(ProductDropdownPopper)(({ theme }) => ({
  width: `100px`,
  height: `100px`,
  margin: `0px 0px 0px 8px`,
}));

const Product3 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI Historic`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.5px`,
  textDecoration: `none`,
  lineHeight: `23px`,
  textTransform: `none`,
  margin: `0px`,
});

const Triangle1 = styled('img')({
  height: `8px`,
  width: `12px`,
  margin: `0px 0px 0px 8px`,
});

const Pricing1 = styled(MUILink)({
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI Historic`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.5px`,
  lineHeight: `23px`,
  textTransform: `none`,
  margin: `0px 0px 0px 30px`,
});

const RightSide1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const LogIn1 = styled(MUILink)({
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI Historic`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.5px`,
  lineHeight: `23px`,
  textTransform: `none`,
  margin: `0px`,
});

const SignUp1 = styled(MUILink)({
  color: `rgba(254, 136, 136, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI Historic`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.5px`,
  lineHeight: `23px`,
  textTransform: `none`,
  margin: `0px 0px 0px 30px`,
});

const XBurger1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 30px`,
});

const Hamburger1 = styled('img')({
  height: `31px`,
  width: `39px`,
  margin: `0px`,
});

const X1 = styled('img')({
  height: `31.17px`,
  width: `31.11px`,
  margin: `0px`,
});

const Logo111 = styled('img')({
  height: `62.44px`,
  width: `60px`,
  objectFit: `cover`,
});

const LeftSide2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const QuestLogoHeader1 = styled('img')({
  height: `37px`,
  width: `128px`,
  margin: `0px`,
});

const Links2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 40px`,
});

const Product4 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const ProductDropdownPoppe2 = styled(ProductDropdownPopper)(({ theme }) => ({
  width: `100px`,
  height: `100px`,
  margin: `0px`,
}));

const Product5 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI Historic`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0.5px`,
  textDecoration: `none`,
  lineHeight: `23px`,
  textTransform: `none`,
  margin: `0px 0px 0px 8px`,
});

const Triangle2 = styled('img')({
  height: `8px`,
  width: `12px`,
  margin: `0px 0px 0px 8px`,
});

const Pricing2 = styled(MUILink)({
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI Historic`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.5px`,
  lineHeight: `23px`,
  textTransform: `none`,
  margin: `0px 0px 0px 30px`,
});

const RightSide2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-end`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const LogIn2 = styled(MUILink)({
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI Historic`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.5px`,
  lineHeight: `23px`,
  textTransform: `none`,
  margin: `0px 0px 0px 30px`,
});

const SignUp2 = styled(MUILink)({
  color: `rgba(254, 136, 136, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI Historic`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.5px`,
  lineHeight: `23px`,
  textTransform: `none`,
  margin: `0px 0px 0px 30px`,
});

const XBurger2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Hamburger2 = styled('img')({
  height: `26.23px`,
  width: `33px`,
  margin: `0px`,
});

const X2 = styled('img')({
  height: `31.17px`,
  width: `31.11px`,
  margin: `0px`,
});

const Menu = styled('div', {
  shouldForwardProp: (prop) => !['data'].includes(prop.toString()),
})(({ data }) => ({
  backgroundColor: `rgba(23, 23, 23, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `35px 36px`,
  boxSizing: `border-box`,
  height: `1043px`,
  width: data.currentVariant === 'screenmobile' ? 'unset' : `375px`,
  margin: `0px`,
  alignSelf: data.currentVariant === 'screenmobile' ? `stretch` : 'unset',
}));

const Links3 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const LinkReact = styled(MUILink)({
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI Historic`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.5px`,
  lineHeight: `21px`,
  textTransform: `none`,
  margin: `0px`,
});

const LinkHtml = styled(MUILink)({
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI Historic`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.5px`,
  lineHeight: `21px`,
  textTransform: `none`,
  margin: `15px 0px 0px 0px`,
});

const LinkPlugin = styled(MUILink)({
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI Historic`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.5px`,
  lineHeight: `21px`,
  textTransform: `none`,
  margin: `15px 0px 0px 0px`,
});

const LinkDocs = styled(MUILink)({
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI Historic`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.5px`,
  lineHeight: `21px`,
  textTransform: `none`,
  margin: `15px 0px 0px 0px`,
});

const LinkPricing = styled(MUILink)({
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI Historic`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.5px`,
  lineHeight: `21px`,
  textTransform: `none`,
  margin: `15px 0px 0px 0px`,
});

const LinkLogIn = styled(MUILink)({
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI Historic`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.5px`,
  lineHeight: `21px`,
  textTransform: `none`,
  margin: `15px 0px 0px 0px`,
});

const LinkSignUp = styled(MUILink)({
  color: `rgba(254, 136, 136, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI Historic`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0.5px`,
  lineHeight: `21px`,
  textTransform: `none`,
  margin: `15px 0px 0px 0px`,
});

function NavbarMowo(props) {
  const { data } = useNavbarMowo();

  return (
    <ScreenDesktop className={props.className} data={data}>
      <Nav data={data}>
        {!(data.currentVariant === 'screentablet') &&
          !(data.currentVariant === 'screenmobile') && (
            <LeftSide>
              <LogoWhiteNormal1
                src={`assets/images/navbarmowo_Logo_white_normal_1.png`}
                loading="lazy"
                alt={'Logo white normal 1'}
              />
              <Links>
                <Product>
                  {false && <ProductDropdownPoppe />}
                  <Product1>{`Product`}</Product1>
                  {false && (
                    <Triangle
                      src={`assets/images/navbarmowo_Triangle.png`}
                      loading="lazy"
                      alt={'Triangle'}
                    />
                  )}
                </Product>
                <Pricing href="#" underline="none">
                  Pricing
                </Pricing>
              </Links>
            </LeftSide>
          )}
        {!(data.currentVariant === 'screentablet') &&
          !(data.currentVariant === 'screenmobile') && (
            <RightSide>
              <LogIn href="#" underline="none">
                Log In
              </LogIn>
              <SignUp href="#" underline="none">
                Sign Up
              </SignUp>
              {false && (
                <XBurger>
                  <Hamburger
                    src={`assets/images/navbarmowo_hamburger.png`}
                    loading="lazy"
                    alt={'hamburger'}
                  />
                  <X
                    src={`assets/images/navbarmowo_X.png`}
                    loading="lazy"
                    alt={'X'}
                  />
                </XBurger>
              )}
            </RightSide>
          )}
        {data.currentVariant === 'screentablet' && (
          <LeftSide1>
            <QuestLogoHeader
              src={`assets/images/navbarmowo_Quest_Logo_header.png`}
              loading="lazy"
              alt={'Quest Logo header'}
            />
            <Links1>
              <Product2>
                {false && <ProductDropdownPoppe1 />}
                <Product3>{`Product`}</Product3>
                <Triangle1
                  src={`assets/images/navbarmowo_Triangle_1.png`}
                  loading="lazy"
                  alt={'Triangle'}
                />
              </Product2>
              <Pricing1 href="#" underline="none">
                Pricing
              </Pricing1>
            </Links1>
          </LeftSide1>
        )}
        {data.currentVariant === 'screentablet' && (
          <RightSide1>
            <LogIn1 href="#" underline="none">
              Log In
            </LogIn1>
            <SignUp1 href="#" underline="none">
              Sign Up
            </SignUp1>
            {false && (
              <XBurger1>
                <Hamburger1
                  src={`assets/images/navbarmowo_hamburger_1.png`}
                  loading="lazy"
                  alt={'hamburger'}
                />
                <X1
                  src={`assets/images/navbarmowo_X_1.png`}
                  loading="lazy"
                  alt={'X'}
                />
              </XBurger1>
            )}
          </RightSide1>
        )}
        {data.currentVariant === 'screenmobile' && (
          <Logo111
            src={`assets/images/navbarmowo_Logo_11_1.png`}
            loading="lazy"
            alt={'Logo-11 1'}
          />
        )}
        {data.currentVariant === 'screenmobile' && (
          <LeftSide2>
            <QuestLogoHeader1
              src={`assets/images/navbarmowo_Quest_Logo_header_1.png`}
              loading="lazy"
              alt={'Quest Logo header'}
            />
            {false && (
              <Links2>
                <Product4>
                  <ProductDropdownPoppe2 />
                  <Product5>{`Product`}</Product5>
                  <Triangle2
                    src={`assets/images/navbarmowo_Triangle_2.png`}
                    loading="lazy"
                    alt={'Triangle'}
                  />
                </Product4>
                <Pricing2 href="#" underline="none">
                  Pricing
                </Pricing2>
              </Links2>
            )}
          </LeftSide2>
        )}
        {data.currentVariant === 'screenmobile' && (
          <RightSide2>
            {false && (
              <LogIn2 href="#" underline="none">
                Log In
              </LogIn2>
            )}
            {false && (
              <SignUp2 href="#" underline="none">
                Sign Up
              </SignUp2>
            )}
            <XBurger2>
              <Hamburger2
                src={`assets/images/navbarmowo_hamburger_2.png`}
                loading="lazy"
                alt={'hamburger'}
              />
              {false && (
                <X2
                  src={`assets/images/navbarmowo_X_2.png`}
                  loading="lazy"
                  alt={'X'}
                />
              )}
            </XBurger2>
          </RightSide2>
        )}
      </Nav>
      {false && (
        <Menu data={data}>
          <Links3>
            <LinkReact href="#" underline="hover">
              React components
            </LinkReact>
            <LinkHtml href="#" underline="hover">
              Websites
            </LinkHtml>
            <LinkPlugin href="#" underline="hover">
              Plugin for Figma
            </LinkPlugin>
            <LinkDocs href="#" underline="hover">
              Docs
            </LinkDocs>
            <LinkPricing href="#" underline="hover">
              Pricing
            </LinkPricing>
            <LinkLogIn href="#" underline="hover">
              Log In
            </LinkLogIn>
            <LinkSignUp href="#" underline="hover">
              Sign Up Now
            </LinkSignUp>
          </Links3>
        </Menu>
      )}
    </ScreenDesktop>
  );
}

export default NavbarMowo;
