/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import useFooterResponsiveSize from './useFooterResponsiveSize';

//These are the possible values for the current variant. Use this to change the currentVariant dynamically.
//Please don't modify
const variantOptions = {
  Property1desktop: 'Property1desktop',
  Property1tablet: 'Property1tablet',
  Property1mobile: 'Property1mobile',
};

const useFooter = () => {
  const [currentVariant, setCurrentVariant] = React.useState(
    variantOptions['Property1desktop']
  );

  const breakpointsVariant = useFooterResponsiveSize();

  React.useEffect(() => {
    if (breakpointsVariant !== currentVariant) {
      setCurrentVariant(breakpointsVariant);
    }
  }, [breakpointsVariant]);

  const data = { currentVariant };

  const fns = { setCurrentVariant };
  return { data, fns };
};

export default useFooter;
