/**********************************************************************
 *
 *   Responsiveness hook generated by Quest
 *
 *   Responsive Logic for the component goes in this hook
 *   If you want to customize the min/max values for the breakpoints, open the component on Quest Editor.
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';

const useHtmlResponsiveSize = () => {
  const [variant, setVariant] = React.useState('Property1HTMLD');

  React.useEffect(() => {
    const handlerProperty1HTMLM = (e) =>
      setVariant((size) => (e.matches ? 'Property1HTMLM' : size));

    const Property1HTMLMSize = window.matchMedia('(max-width: 572px)');
    setVariant((size) =>
      Property1HTMLMSize.matches ? 'Property1HTMLM' : size
    );
    Property1HTMLMSize.addEventListener('change', handlerProperty1HTMLM);

    const handlerProperty1HTMLT = (e) =>
      setVariant((size) => (e.matches ? 'Property1HTMLT' : size));

    const Property1HTMLTSize = window.matchMedia(
      '(min-width: 573px) and (max-width: 1104px)'
    );
    setVariant((size) =>
      Property1HTMLTSize.matches ? 'Property1HTMLT' : size
    );
    Property1HTMLTSize.addEventListener('change', handlerProperty1HTMLT);

    const handlerProperty1HTMLD = (e) =>
      setVariant((size) => (e.matches ? 'Property1HTMLD' : size));

    const Property1HTMLDSize = window.matchMedia('(min-width: 1105px)');
    setVariant((size) =>
      Property1HTMLDSize.matches ? 'Property1HTMLD' : size
    );
    Property1HTMLDSize.addEventListener('change', handlerProperty1HTMLD);
  }, []);

  return variant;
};

export default useHtmlResponsiveSize;
